"""Generate a conservative corpus project skeleton from a factory manifest."""
from __future__ import annotations
from pathlib import Path
import argparse, json

CONTRACT = {
    "$schema":"https://json-schema.org/draft/2020-12/schema",
    "contract":"hawkinsnick-epigraphic-corpus-interoperability",
    "version":"1.1.0",
    "principles":{
        "source_attribution_required":True,
        "source_integrity_hash_required":True,
        "uncertainty_preserved":True,
        "unknown_physical_object_count_is_null":True,
        "cross_language_pooling_default":False,
        "cross_project_links_create_independent_witnesses":False,
        "language_or_script_identity_inferred_from_links":False,
        "decipherment_claimed":False,
    },
}

def write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        raise SystemExit(f"Refusing to overwrite {path}")
    path.write_text(text, encoding="utf-8")

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("manifest")
    ap.add_argument("output")
    args=ap.parse_args()
    m=json.loads(Path(args.manifest).read_text(encoding="utf-8"))
    out=Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    contract=dict(CONTRACT)
    contract["profile"]=m["record_profile"]
    write(out/"project.json", json.dumps({
        "project":m["name"],"adapter":"unimplemented","scope":"Source discovery scaffold",
        "record_unit":m["record_profile"],"python_minimum":"3.10","status":"scaffold"
    },indent=2)+"\n")
    write(out/"schemas/interoperability-contract.json",json.dumps(contract,indent=2)+"\n")
    write(out/"data/sources.json",'{"sources":[]}\n')
    write(out/"data/records.json","[]\n")
    write(out/"VERSION","0.1.0\n")
    write(out/"README.md",f"# {m['name']}\n\nGenerated by Corpus Factory. Source rights and scholarly review are unresolved until explicitly documented.\n")
    print(out)

if __name__=="__main__":
    main()
